---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam' 
summary: Saiba mais sobre as mudanças mais recentes nos serviços de nuvem que fazem parte da plataforma BlueXP . 
---
= Mudanças recentes em BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as mudanças mais recentes nos serviços de nuvem que fazem parte da plataforma BlueXP . Para obter um histórico de versões completo, aceda ao link:release-notes-index.html["conjunto completo de notas de lançamento"] para cada serviço individual.



== Recursos administrativos

Esta seção descreve novos recursos relacionados aos recursos de administração do BlueXP : Contas, conetores, credenciais de provedor de nuvem e muito mais.



=== 14 de abril de 2025



==== Conetor 3.9.51

Esta versão do conetor BlueXP  inclui pequenas melhorias de segurança e correções de bugs.

Neste momento, a versão 3.9.51 está disponível para o modo padrão e modo restrito.



==== Gerenciamento de identidade e acesso do BlueXP  (IAM)

* Os usuários sem o administrador Org ou pasta ou administrador de projeto devem ter uma função de proteção contra ransomware para ter acesso à proteção contra ransomware. Você pode atribuir a um usuário uma de duas funções: Administrador de proteção contra ransomware ou visualizador de proteção contra ransomware.
* Os usuários sem o administrador da organização ou pasta ou administrador do projeto devem ter uma função do Keystone para ter acesso ao Keystone. Você pode atribuir a um usuário uma de duas funções: Administrador do Keystone ou visualizador do Keystone.
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso."^]

* Se você tiver a função de administrador de Org ou pasta ou administrador de projeto, agora poderá associar uma assinatura do Keystone a um projeto do IAM. A associação de uma assinatura do Keystone a um projeto do IAM permite que você controle o acesso ao Keystone no BlueXP .




=== 28 de março de 2025



==== Lançamento do modo privado (3,9.50)

Uma nova versão do modo privado está agora disponível para transferência a partir do https://mysupport.netapp.com/site/downloads["Site de suporte da NetApp"^]

A versão 3.9.50 inclui atualizações para os seguintes componentes e serviços do BlueXP .

[cols="3*"]
|===
| Componente ou serviço | Versão incluída nesta versão | Alterações desde a versão anterior do modo privado 


| Conetor | 3,9.50, 3.9.49 | Aceda ao https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["Novidades na página do conetor BlueXP"] e consulte as alterações incluídas nas versões 3.9.50 e 3,9.49. 


| Backup e recuperação | 17 de março de 2025 | Aceda ao https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["Novidades na página de backup e recuperação do BlueXP"^] e consulte as alterações incluídas na versão de Março de 2024. 


| Classificação | 10 Março 2025 (versão 1,41) | Aceda ao https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["Novidades na página de classificação do BlueXP"^] e consulte as alterações incluídas nas versões 1,38 a 1.371.41. 
|===
Para obter mais detalhes sobre o modo privado, incluindo como atualizar, consulte o seguinte:

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Saiba mais sobre o modo privado"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Saiba como começar a usar o BlueXP  no modo privado"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Saiba como atualizar o conetor ao usar o modo privado"]




=== 10 de março de 2025



==== Conetor 3.9.50

Esta versão do conetor BlueXP  inclui pequenas melhorias de segurança e correções de bugs.

* O gerenciamento de sistemas Cloud Volumes ONTAP agora é suportado por conetores que têm o SELinux habilitado no sistema operacional.
+
https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/using_selinux/getting-started-with-selinux_using-selinux["Saiba mais sobre o SELinux"^]



Neste momento, a versão 3.9.50 está disponível para o modo padrão e modo restrito.



==== NetApp Keystone beta disponível no BlueXP

O NetApp Keystone estará disponível em breve no BlueXP  e agora está em beta. Você pode acessar a página de inscrição para o NetApp Keystone beta na barra de navegação à esquerda do BlueXP .



== Alertas



=== 7 de outubro de 2024



==== Página da lista de alertas do BlueXP

É possível identificar rapidamente clusters do ONTAP com baixa capacidade ou baixa performance, avaliar a extensão da disponibilidade e identificar riscos de segurança. Você pode visualizar alertas relacionados a capacidade, performance, proteção, disponibilidade, segurança e configuração.



==== Detalhes dos alertas

Você pode detalhar os detalhes do alerta e encontrar recomendações.



==== Exibir detalhes do cluster vinculados ao Gerenciador de sistema do ONTAP

Com os alertas do BlueXP , você pode visualizar os alertas associados ao seu ambiente de storage do ONTAP e detalhar os detalhes vinculados ao Gerenciador de sistemas do ONTAP.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Saiba mais sobre os alertas do BlueXP"].



== Amazon FSX para ONTAP



=== 04 de maio de 2025



==== Suporte de resposta do Rastreador

O Tracker agora fornece respostas à API para que você possa ver a saída da API REST relacionada à tarefa.



==== Suporte de autenticação de link para o AWS Secrets Manager

Agora você tem a opção de usar segredos do AWS Secrets Manager para autenticar links para que você não precise usar credenciais armazenadas em cargas de trabalho do BlueXP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Conete-se a um sistema de arquivos FSX for ONTAP com um link do Lambda"]



==== Implemente as melhores práticas para um sistema de arquivos FSX for ONTAP

O BlueXP  workloads fornece um painel onde você pode verificar o status bem arquitetado das configurações do sistema de arquivos. Você pode aproveitar essa análise para implementar as práticas recomendadas para seus sistemas de arquivos FSX for ONTAP. A análise de configuração do sistema de arquivos inclui as seguintes configurações: Limite de capacidade SSD, snapshots locais programados, backups programados do FSX para ONTAP, disposição de dados em categorias e replicação de dados remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Saiba mais sobre a análise bem arquitetada para configurações do sistema de arquivos"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["Implemente as práticas recomendadas para seus sistemas de arquivos"]




==== Notificação bem arquitetada para problemas do sistema de arquivos

No console do BlueXP , os sistemas de arquivos FSX for ONTAP com problemas bem arquitetados agora exibem uma notificação no Canvas indicando quando os sistemas de arquivos têm problemas para corrigir.



==== Terminologia de permissões atualizada

A interface do usuário e a documentação de fábrica da carga de trabalho agora usam "somente leitura" para se referir a permissões de leitura e "leitura-gravação" para se referir a permissões de automação.



=== 30 de março de 2025



==== IAM:Atualização de permissão SimulatePermissionPolicy

Agora você pode gerenciar a `iam:SimulatePrincipalPolicy` permissão no console do BlueXP  ao adicionar credenciais adicionais de conta da AWS ou adicionar uma nova funcionalidade de workload, como o workload do GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de alteração de referência de permissões"^]



=== 02 de março de 2025



==== Eventos CloudShell no Tracker

Sempre que você usar o CloudShell para executar operações do FSX for ONTAP a partir de cargas de trabalho do BlueXP , os eventos aparecem no Rastreador.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["Saiba como monitorar e acompanhar as operações do FSX for ONTAP no BlueXP"^]



== Storage Amazon S3



=== 5 de março de 2023



==== Capacidade de adicionar novos buckets do BlueXP

Você teve a capacidade de visualizar buckets do Amazon S3 no BlueXP  Canvas por um tempo. Agora você pode adicionar novos buckets e alterar propriedades para buckets existentes diretamente do BlueXP . https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["Veja como adicionar novos buckets do Amazon S3"].



== Storage Azure Blob



=== 5 de junho de 2023



==== Capacidade de adicionar novas contas de storage do BlueXP

Você já teve a capacidade de visualizar o armazenamento de Blobs do Azure no BlueXP  Canvas por algum tempo. Agora você pode adicionar novas contas de armazenamento e alterar propriedades para contas de armazenamento existentes diretamente do BlueXP . https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["Veja como adicionar novas contas de armazenamento Azure Blob"].



== Azure NetApp Files



=== 13 de janeiro de 2025



==== Recursos de rede agora suportados no BlueXP

Ao configurar um volume no Azure NetApp Files a partir do BlueXP , agora você pode indicar recursos de rede. Isso se alinha à funcionalidade disponível no Azure NetApp Files nativo.



=== 12 de junho de 2024



==== Nova permissão necessária

Agora é necessária a permissão a seguir para gerenciar volumes do Azure NetApp Files a partir do BlueXP :

Microsoft.Network/virtualNetworks/subnets/read

Esta permissão é necessária para ler uma sub-rede virtual.

Se você estiver gerenciando o Azure NetApp Files do BlueXP  no momento, precisará adicionar essa permissão à função personalizada associada ao aplicativo Microsoft Entra que você criou anteriormente.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Saiba como configurar um aplicativo Microsoft Entra e exibir as permissões de função personalizadas"].



=== 22 de abril de 2024



==== Modelos de volume já não são suportados

Você não pode mais criar um volume a partir de um modelo. Essa ação foi associada ao serviço de correção do BlueXP , que não está mais disponível.



== Backup e recuperação



=== 16 de abril de 2025

Esta versão de backup e recuperação do BlueXP  inclui as seguintes atualizações.



==== Melhorias na IU

Esta versão melhora sua experiência simplificando a interface:

* A remoção da coluna agregada das tabelas volumes, juntamente com as colunas Política de snapshot, Política de backup e Política de replicação da tabela volume no Painel V2, resulta em um layout mais simplificado.
* A exclusão de ambientes de trabalho não ativados da lista suspensa torna a interface menos organizada, a navegação mais eficiente e o carregamento mais rápido.
* Enquanto a classificação na coluna Tags está desativada, você ainda pode visualizar as tags, garantindo que informações importantes permaneçam facilmente acessíveis.
* A remoção de etiquetas nos ícones de proteção contribui para uma aparência mais limpa e diminui o tempo de carregamento.
* Durante o processo de ativação do ambiente de trabalho, uma caixa de diálogo exibe um ícone de carregamento para fornecer feedback até que o processo de descoberta esteja concluído, aumentando a transparência e a confiança nas operações do sistema.




==== Painel de controlo de volume melhorado (pré-visualização)

O Painel de volume agora é carregado em menos de 10 segundos, fornecendo uma interface muito mais rápida e eficiente. Esta versão de pré-visualização está disponível para clientes selecionados, oferecendo-lhes uma visão antecipada dessas melhorias.



==== Suporte para armazenamento de objetos Wasabi de terceiros (Preview)

O backup e a recuperação do BlueXP  agora estendem seu suporte a armazenamentos de objetos de terceiros com foco principal no Wasabi. Este novo recurso de visualização permite que você aproveite qualquer armazenamento de objetos compatível com S3 para suas necessidades de backup e recuperação.



===== Introdução ao Wasabi

Para começar a usar o armazenamento de terceiros como um armazenamento de objetos, você deve habilitar um sinalizador no BlueXP  Connector. Em seguida, você pode inserir os detalhes de conexão do seu armazenamento de objetos de terceiros e integrá-los aos fluxos de trabalho de backup e recuperação.

.Passos
. SSH em seu conetor.
. Vá para o contentor do servidor cbs de backup e recuperação do BlueXP :
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Abra o `default.json` arquivo dentro `config` da pasta via VIM ou qualquer outro editor:
+
[listing]
----
vi default.json
----
.  `allow-s3-compatible`Modificar : false para `allow-s3-compatible`: true.
. Salve as alterações.
. Saia do recipiente.
. Reinicie o contentor do servidor cbs de backup e recuperação do BlueXP .


.Resultado
Depois que o contentor estiver LIGADO novamente, abra a IU de backup e recuperação do BlueXP . Ao iniciar um backup ou editar uma estratégia de backup, você verá o novo provedor "compatível com S3" listado junto com outros provedores de backup da AWS, Microsoft Azure, Google Cloud, StorageGRID e ONTAP S3.



===== Limitações do modo de visualização

Embora esse recurso esteja na visualização, considere as seguintes limitações:

* Bring Your own Bucket (BYOB) não é suportado.
* A ativação do DataLock em uma política não é suportada.
* A ativação do modo de arquivamento em uma política não é suportada.
* Somente ambientes ONTAP locais são compatíveis.
* O MetroCluster não é suportado.
* As opções para habilitar a criptografia no nível do bucket não são suportadas.


Durante essa visualização, recomendamos que você explore esse novo recurso e forneça feedback sobre a integração com armazenamentos de objetos de terceiros antes que a funcionalidade completa seja implementada.



=== 17 de março de 2025

Esta versão de backup e recuperação do BlueXP  inclui as seguintes atualizações.



==== Navegação de instantâneos SMB

Esta atualização de backup e recuperação do BlueXP  resolveu um problema que impedia os clientes de navegar em snapshots locais em um ambiente SMB.



==== Atualização de ambiente do AWS GovCloud

Essa atualização de backup e recuperação do BlueXP  corrigiu um problema que impedia a interface do usuário de se conetar a um ambiente AWS GovCloud devido a erros de certificado TLS. O problema foi resolvido usando o nome do host do conetor BlueXP  em vez do endereço IP.



==== Limites de retenção da política de backup

Anteriormente, a IU de backup e recuperação do BlueXP  limitava os backups a 999 cópias, enquanto a CLI permitia mais. Agora, você pode anexar até 4.000 volumes a uma política de backup e incluir volumes 1.018 não anexados a uma política de backup. Esta atualização inclui validações adicionais que impedem a superação desses limites.



==== Ressincronizar a nuvem da SnapMirror

Essa atualização garante que o ressync do SnapMirror Cloud não possa ser iniciado a partir do backup e recuperação do BlueXP  para versões ONTAP não suportadas depois que uma relação do SnapMirror for excluída.



=== 21 de fevereiro de 2025

Esta versão de backup e recuperação do BlueXP  inclui as seguintes atualizações.



==== Indexação de alto desempenho

O backup e a recuperação do BlueXP  introduz um recurso de indexação atualizado que torna a indexação de dados no ambiente de trabalho de origem mais eficiente. O novo recurso de indexação inclui atualizações para a interface do usuário, melhor desempenho do método de pesquisa e restauração de dados, atualizações para recursos de pesquisa global e melhor escalabilidade.

Aqui está um detalhamento das melhorias:

* *Consolidação de pastas*: A versão atualizada agrupa as pastas usando nomes que incluem identificadores específicos, tornando o processo de indexação mais suave.
* *Compactação de arquivos Parquet*: A versão atualizada reduz o número de arquivos usados para indexar cada volume, simplificando o processo e eliminando a necessidade de um banco de dados extra.
* *Escale-out com mais sessões*: A nova versão adiciona mais sessões para lidar com tarefas de indexação, acelerando o processo.
* *Suporte para vários contentores de índice*: A nova versão usa vários contentores para gerenciar e distribuir melhor as tarefas de indexação.
* *Fluxo de trabalho de índice dividido*: A nova versão divide o processo de indexação em duas partes, aumentando a eficiência.
* *Melhoria da simultaneidade*: A nova versão permite excluir ou mover diretórios ao mesmo tempo, acelerando o processo de indexação.


.Quem se beneficia desta funcionalidade?
O novo recurso de indexação está disponível para todos os novos clientes.

.Como você ativa a indexação?
Antes de poder utilizar o método de pesquisa e restauro de restaurar dados, tem de ativar a "Indexação" em cada ambiente de trabalho de origem a partir do qual pretende restaurar volumes ou ficheiros. Isso permite que o Catálogo indexado acompanhe cada volume e cada arquivo de backup, tornando suas pesquisas rápidas e eficientes.

Ative a indexação no ambiente de trabalho de origem selecionando a opção "Ativar indexação" quando estiver a efetuar uma pesquisa e restauro.

Para obter mais informações, consulte a documentação https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Como restaurar dados do ONTAP usando pesquisar  Restaurar"].

.Escala suportada
O novo recurso de indexação suporta o seguinte:

* Eficiência de pesquisa global em menos de 3 minutos
* Até 5 bilhões de arquivos
* Até 5000 volumes por cluster
* Até 100K instantâneos por volume
* O tempo máximo para indexação da linha de base é inferior a 7 dias. O tempo real irá variar dependendo do seu ambiente.




==== Melhorias de desempenho de pesquisa global

Esta versão também inclui melhorias no desempenho de pesquisa global. Agora você verá indicadores de progresso e resultados de pesquisa mais detalhados, incluindo a contagem de arquivos e o tempo necessário para a pesquisa. Os contentores dedicados para pesquisa e indexação garantem que as pesquisas globais sejam concluídas em menos de cinco minutos.

Observe estas considerações relacionadas à pesquisa global:

* O novo índice não é executado em instantâneos rotulados como por hora.
* O novo recurso de indexação funciona apenas em snapshots no FlexVols e não em snapshots no FlexGroups.




== Classificação



=== 12 de maio de 2025



==== Versão 1,43

Esta versão de classificação BlueXP  inclui:

.Priorizar exames de classificação
A classificação BlueXP  agora suporta a capacidade de priorizar exames de mapa e classificação, além de exames somente de mapeamento, permitindo selecionar quais exames são concluídos primeiro. A priorização dos exames de mapa e classificação é suportada durante e antes do início dos exames. Se optar por priorizar um exame enquanto este está em andamento, os exames de mapeamento e classificação são priorizados.

Para obter mais informações, link:task-managing-repo-scanning.html#prioritize-scans["Priorizar exames"]consulte .

.Suporte para categorias de dados de informações pessoais (PII) canadenses
As análises de classificação do BlueXP  agora identificam categorias de dados de PII canadenses para informações bancárias, número de passaporte, número de seguro social e número de carteira de motorista e número de cartão de saúde para todas as províncias e territórios.

Para obter mais informações detalhadas, xref:reference-private-data-categories.adoc#types-of-personal-data[Categorias de dados pessoais]consulte .

.Classificação personalizada (pré-visualização)
A classificação BlueXP  agora suporta classificações personalizadas para exames de mapa e classificação. Com classificações personalizadas, você pode personalizar as digitalizações BlueXP  para capturar dados específicos da sua organização para garantir a conformidade com expressões regulares. Esta funcionalidade está atualmente em pré-visualização.

Para obter mais informações, xref:task-custom-classification.adoc[Adicione classificações personalizadas]consulte .

.Separador Pesquisas guardadas
A guia **políticas** foi renomeada xref:task-using-policies.html[**Pesquisas salvas**]. A funcionalidade é a mesma.

.Enviar eventos de digitalização para a linha do tempo do BlueXP 
A classificação BlueXP  agora suporta o envio de eventos de classificação (quando um exame é iniciado e quando termina) para o link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Linha do tempo de BlueXP"^].

.Atualizações de segurança
* O pacote keras foi atualizado, atenuando vulnerabilidades (BDSA-2025-0107 e BDSA-2025-1984).
* A configuração de contentores do Docker foi atualizada. O contentor não tem mais acesso às interfaces de rede do host para criar pacotes de rede brutos. Ao reduzir o acesso desnecessário, a atualização atenua potenciais riscos de segurança.


.Melhorias de performance
Melhorias de código foram implementadas para reduzir o uso de RAM e melhorar o desempenho geral da classificação BlueXP .

.Correções de bugs
Os bugs que fizeram com que as verificações do StorageGRID falhassem, as opções de filtro da página de investigação não carregassem e a avaliação de descoberta de dados não baixassem para avaliações de alto volume foram corrigidos.



=== 14 de abril de 2025



==== Versão 1,42

Esta versão de classificação BlueXP  inclui:

.Digitalização em massa para ambientes de trabalho
A classificação BlueXP  agora suporta operações em massa para ambientes de trabalho. Pode optar por ativar Mapeamento de digitalizações, ativar mapa e classificar digitalizações, desativar digitalizações ou criar uma configuração personalizada entre volumes no ambiente de trabalho. Se você fizer uma seleção para um volume individual, ele substituirá a seleção em massa. Para executar uma operação em massa, navegue até a página **Configuração** e faça a sua seleção.

.Baixe o relatório de investigação localmente
A classificação BlueXP  agora suporta a capacidade de baixar relatórios de investigação de dados localmente para visualizar no navegador. Se você escolher a opção local, a investigação de dados estará disponível apenas no formato CSV e exibirá apenas as primeiras 10.000 linhas de dados.

Para obter mais informações, link:task-investigate-data.html#create-the-data-investigation-report["Investigue os dados armazenados na sua organização com a classificação BlueXP"]consulte .



=== 10 de março de 2025



==== Versão 1,41

Esta versão de classificação do BlueXP  inclui melhorias gerais e correções de bugs. Também inclui:

.Estado do exame
A classificação BlueXP  agora rastreia o progresso em tempo real do mapeamento _initial_ e verificações de classificação em um volume. Barras progressivas separadas rastreiam os exames de mapeamento e classificação, apresentando uma porcentagem do total de arquivos digitalizados. Você também pode passar o Mouse sobre uma barra de progresso para ver o número de arquivos digitalizados e o total de arquivos. O acompanhamento do estado das suas digitalizações cria informações mais profundas sobre o progresso da digitalização, permitindo-lhe planear melhor as suas digitalizações e compreender a alocação de recursos.

Para ver o status das suas digitalizações, navegue até **Configuração** na classificação BlueXP  e selecione **Configuração do ambiente de trabalho**. O progresso é exibido na linha para cada volume.



=== 19 de fevereiro de 2025



==== Versão 1,40

Esta versão de classificação do BlueXP  inclui as seguintes atualizações.

.Suporte para RHEL 9,5
Esta versão fornece suporte para Red Hat Enterprise Linux v9,5, além de versões anteriormente suportadas. Isso é aplicável a qualquer instalação manual no local da classificação do BlueXP , incluindo implantações em locais escuros.

Os sistemas operacionais a seguir requerem o uso do motor de contentor Podman, e eles exigem a classificação BlueXP  versão 1,30 ou superior: Red Hat Enterprise Linux versão 8,8, 8,10, 9,0, 9,1, 9,2, 9,3, 9,4 e 9,5.

.Priorizar digitalizações somente de mapeamento
Ao realizar exames somente de mapeamento, você pode priorizar os exames mais importantes. Este recurso ajuda quando você tem muitos ambientes de trabalho e quer garantir que as verificações de alta prioridade sejam concluídas primeiro.

Por padrão, as digitalizações são enfileiradas com base na ordem em que são iniciadas. Com a capacidade de priorizar digitalizações, agora você pode mover digitalizações para a frente da fila. Várias digitalizações podem ser priorizadas. A prioridade é designada em uma ordem de primeira entrada e primeira saída, o que significa que a primeira digitalização que você prioriza se move para a frente da fila; a segunda digitalização que você prioriza se torna segunda na fila, e assim por diante.

A prioridade é concedida de uma só vez. As redigitalizações automáticas de dados de mapeamento ocorrem na ordem padrão.

A priorização é limitada a link:concept-cloud-compliance.html["digitalizações apenas de mapeamento"]; ela não está disponível para mapear e classificar digitalizações.

Para obter mais informações, link:task-managing-repo-scanning.html#prioritize-scans["Priorizar exames"]consulte .

.Tente novamente todas as digitalizações
A classificação BlueXP  agora suporta a capacidade de tentar em lote novamente todas as digitalizações com falha.

Agora você pode tentar novamente digitalizações em uma operação em lote com a função **Repetir tudo**. Se as verificações de classificação estiverem falhando devido a um problema temporário, como uma interrupção da rede, você pode tentar novamente todas as verificações ao mesmo tempo com um botão em vez de tentar novamente individualmente. As digitalizações podem ser tentadas quantas vezes forem necessárias.

Para tentar novamente todas as digitalizações:

. No menu classificação BlueXP , selecione *Configuração*.
. Para tentar novamente todas as digitalizações com falha, selecione *Repetir todas as digitalizações*.


.Precisão melhorada do modelo de categorização
A precisão do modelo de aprendizado de máquina para link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["categorias predefinidas"]melhorou em 11%.



=== 22 de janeiro de 2025



==== Versão 1,39

Esta versão de classificação do BlueXP  atualiza o processo de exportação para o relatório de investigação de dados. Esta atualização de exportação é útil para realizar análises adicionais sobre seus dados, criar visualizações adicionais sobre os dados ou compartilhar os resultados de sua investigação de dados com outras pessoas.

Anteriormente, a exportação do relatório de investigação de dados estava limitada a 10.000 linhas. Com esta versão, o limite foi removido para que você possa exportar todos os seus dados. Essa alteração permite exportar mais dados dos relatórios de investigação de dados, fornecendo mais flexibilidade na análise de dados.

Você pode escolher o ambiente de trabalho, volumes, pasta de destino e formato JSON ou CSV. O nome do arquivo exportado inclui um carimbo de data/hora para ajudá-lo a identificar quando os dados foram exportados.

Os ambientes de trabalho suportados incluem:

* Cloud Volumes ONTAP
* FSX para ONTAP
* ONTAP
* Compartilhar grupo


A exportação de dados do relatório de investigação de dados tem as seguintes limitações:

* O número máximo de Registros para download é de 500 milhões. Por tipo (arquivos, diretórios e tabelas)
* Espera-se que um milhão de Registros leve cerca de 35 minutos para exportação.


Para obter detalhes sobre a investigação de dados e o relatório, https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Investigue os dados armazenados na sua organização"] consulte .



=== 16 de dezembro de 2024



==== Versão 1,38

Esta versão de classificação do BlueXP  inclui melhorias gerais e correções de bugs.



== Cloud Volumes ONTAP



=== 12 de maio de 2025



==== Descoberta de implantações feitas pelo marketplace do Azure no BlueXP

O BlueXP  agora tem a capacidade de descobrir os sistemas Cloud Volumes ONTAP implantados diretamente no marketplace do Azure. Isso significa que agora você pode adicionar e gerenciar esses sistemas como ambientes de trabalho no BlueXP , assim como qualquer outro sistema Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["Implante o Cloud Volumes ONTAP a partir do marketplace do Azure"^]



==== Capacidade de categorizar dados para locatários do Azure

Agora você pode habilitar a disposição em camadas para um locatário do Azure em um cenário em que o ambiente de trabalho do Cloud Volumes ONTAP é criado por um locatário e o BlueXP  Connector é criado por outro. Usando essa funcionalidade, você pode usar o mesmo conetor para categorizar dados para vários locatários do Azure.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["Requisitos para categorizar dados para um locatário do Azure"^]



=== 16 de abril de 2025



==== Novas regiões com suporte no Azure

Agora você pode implantar o Cloud Volumes ONTAP 9.12.1 GA e versões posteriores em zonas de disponibilidade únicas e múltiplas no Azure nas seguintes regiões. Isso inclui suporte para implantações de nó único e alta disponibilidade (HA).

* Espanha Central
* México Central


Para obter uma lista de todas as regiões, consulte https://bluexp.netapp.com/cloud-volumes-global-regions["Mapa das Regiões globais no Azure"^]a .



=== 14 de abril de 2025



==== Criação automatizada de VM de storage por meio das APIs no Google Cloud

Agora você pode usar as APIs do BlueXP  para automatizar a criação de VM de storage no Google Cloud. Você usa esse recurso nas configurações de alta disponibilidade (HA) do Cloud Volumes ONTAP e agora também pode usá-lo em implantações de nó único. Usando as APIs do BlueXP , você pode facilmente criar, renomear e excluir VMs de storage adicionais de fornecimento de dados no ambiente do Google Cloud, sem a necessidade de configurar manualmente as interfaces de rede, LIFs e LIFs de gerenciamento necessárias. Essa automação simplifica o processo de gerenciamento de VMs de storage.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Gerencie VMs de storage de fornecimento de dados para Cloud Volumes ONTAP no Google Cloud"^]



== Cloud Volumes Service para Google Cloud



=== 9 de setembro de 2020



==== Suporte ao Cloud Volumes Service para Google Cloud

Agora você pode gerenciar o Cloud Volumes Service para Google Cloud diretamente do BlueXP :

* Configure e crie um ambiente de trabalho
* Crie e gerencie volumes NFSv3 e NFSv4,1 para clientes Linux e UNIX
* Crie e gerencie volumes SMB 3.x para clientes Windows
* Criar, excluir e restaurar snapshots de volume




== Copiar e sincronizar



=== 2 de fevereiro de 2025



==== Novo suporte de SO para agente de dados

O corretor de dados agora é compatível com hosts que executam Red Hat Enterprise 9,4, Ubuntu 23,04 e Ubuntu 24,04.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Veja os requisitos do host Linux"].



=== 27 de outubro de 2024



==== Correções de bugs

Atualizamos o serviço de cópia e sincronização do BlueXP  e o corretor de dados para corrigir alguns bugs. A nova versão do Data Broker é 1,0.56.



=== 16 de setembro de 2024



==== Correções de bugs

Atualizamos o serviço de cópia e sincronização do BlueXP  e o corretor de dados para corrigir alguns bugs. A nova versão do Data Broker é 1,0.55.



== Consultor digital



=== 05 de março de 2025



==== Consultor de atualização

* Usando o Pacote de Qualificação de disco (DQP), agora você pode atualizar automaticamente os controladores de disco e o firmware do dispositivo de armazenamento de acordo com critérios predefinidos de integridade e desempenho. Isso reduz possíveis falhas e aumenta a confiabilidade geral do sistema.
* O banco de dados de fuso horário (DB) foi introduzido para manter automaticamente o alinhamento do sistema com as definições de fuso horário mais recentes. Isso garante que as operações dependentes do tempo continuem sem problemas, mesmo quando as regras de fuso horário mudam.




=== 12 de dezembro de 2024



==== Consultor de atualização

Agora você pode visualizar o firmware de armazenamento, o firmware do SP/BMC e o Autonomous ransomware Package (ARP) recomendados para uma atualização. link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["Saiba como visualizar as recomendações de atualização de firmware"].



=== 04 de dezembro de 2024



==== Widget AutoSupport

O widget AutoSupport foi adicionado à tela principal do painel para alertar os clientes sobre os problemas relacionados ao status do AutoSupport.



== Carteira digital



=== 10 de março de 2025



==== Capacidade de remover assinaturas

Agora você pode remover assinaturas da carteira digital se você tiver cancelado a assinatura delas.



==== Exibir a capacidade consumida para assinaturas do Marketplace

Ao visualizar as assinaturas PAYGO, agora você pode visualizar a capacidade consumida da assinatura.



=== 10 de fevereiro de 2025

A carteira digital BlueXP  foi redesenhada para facilitar o uso e agora fornece gerenciamento adicional de assinaturas e licenças.



==== Novo painel de visão geral

A página inicial da carteira digital tem um painel atualizado das suas licenças do NetApp e subscrições do Marketplace, com a capacidade de detalhar serviços específicos, tipos de licença e ações necessárias.



==== Configurando assinaturas para credenciais

A carteira digital BlueXP  agora permite configurar suas assinaturas para credenciais de provedor. Normalmente, você faz isso quando você se inscreve pela primeira vez em uma assinatura do Marketplace ou em um contrato anual. A alteração das credenciais da assinatura anteriormente só poderia ser feita na página credenciais.



==== Associar assinaturas às organizações

Agora você pode atualizar a organização à qual uma assinatura está associada diretamente da carteira digital.



==== Gerenciamento de licenças do Cloud volume ONTAP

Agora, você gerencia licenças do Cloud Volumes ONTAP através da página inicial ou da guia *licenças diretas*. Use a guia *assinaturas do Marketplace* para exibir suas informações de assinatura.



=== 5 de março de 2024



==== Recuperação de desastres da BlueXP

A carteira digital BlueXP  agora permite gerenciar licenças para recuperação de desastres do BlueXP . Você pode adicionar licenças, atualizar licenças e exibir detalhes sobre a capacidade licenciada.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Saiba como gerenciar licenças para serviços de dados do BlueXP "]



=== 30 de julho de 2023



==== Melhorias nos relatórios de uso

Várias melhorias nos relatórios de uso do Cloud Volumes ONTAP estão agora disponíveis:

* A unidade TIB está agora incluída no nome das colunas.
* Um novo campo _node(s)_ para números de série está agora incluído.
* Uma nova coluna _Workload Type_ agora está incluída no relatório de uso das VMs de armazenamento.
* Os nomes dos ambientes de trabalho agora estão incluídos nos relatórios de uso de volume e VMs de armazenamento.
* O tipo de volume _file_ agora é rotulado como _Primary (Read/Write)_.
* O tipo de volume _secondary_ agora é rotulado como _Secondary (DP)_.


Para obter mais informações sobre os relatórios de uso, https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Transfira relatórios de utilização"] consulte .



== Recuperação de desastres



=== 16 de abril de 2025

Versão 4.2.2



==== Detecção programada para VMs

A recuperação de desastres do BlueXP  realiza a descoberta a cada 24 horas. Com esta versão, agora você pode personalizar o cronograma de descoberta para atender às suas necessidades e reduzir o impactos no desempenho quando necessário. Por exemplo, se você tiver um grande número de VMs, poderá definir a programação de descoberta para ser executada a cada 48 horas. Se você tiver um pequeno número de VMs, poderá definir o agendamento de descoberta para ser executado a cada 12 horas.

Se você não deseja agendar a descoberta, você pode desativar a opção de descoberta agendada e atualizar a descoberta manualmente a qualquer momento.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Adicione sites do vCenter Server"] consulte .



==== Suporte ao datastore do grupo de recursos

Anteriormente, você poderia criar grupos de recursos apenas por VMs. Com essa versão, você pode criar um grupo de recursos por datastores. Quando você estiver criando um plano de replicação e criando um grupo de recursos para esse plano, todas as VMs em um datastore serão listadas. Isso é útil se você tiver um grande número de VMs e quiser agrupá-las por datastore.

Você pode criar um grupo de recursos com um datastore das seguintes maneiras:

* Ao adicionar um grupo de recursos usando datastores, você pode ver uma lista de datastores. Você pode selecionar um ou mais datastores para criar um grupo de recursos.
* Ao criar um plano de replicação e criar um grupo de recursos dentro do plano, você pode ver as VMs nos datastores.


Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



==== Notificações de avaliação gratuita ou expiração de licença

Esta versão fornece notificações de que o teste gratuito expirará em 60 dias para garantir que você tenha tempo para obter uma licença. Esta versão também fornece notificações no dia em que a licença expira.



==== Notificação de atualizações de serviço

Com esta versão, um banner aparece na parte superior para indicar que os serviços estão sendo atualizados e que o serviço é colocado no modo de manutenção. O banner aparece quando o serviço está sendo atualizado e desaparece quando a atualização é concluída. Embora possa continuar a trabalhar na IU enquanto a atualização estiver em curso, não é possível enviar novos trabalhos. Os trabalhos agendados serão executados após a conclusão da atualização e o serviço retornará ao modo de produção.



=== 10 de março de 2025

Versão 4.2.1



==== Suporte a proxy inteligente

O conetor BlueXP  suporta proxy inteligente. O proxy inteligente é uma maneira leve, segura e eficiente de conectar seu ambiente local ao serviço BlueXP . Ele fornece uma conexão segura entre o seu ambiente e o serviço BlueXP  sem exigir uma VPN ou acesso direto à Internet. Essa implementação de proxy otimizada descarrega o tráfego da API dentro da rede local.

Quando um proxy é configurado, a recuperação de desastres do BlueXP  tenta se comunicar diretamente com o VMware ou o ONTAP e usa o proxy configurado se a comunicação direta falhar.

A implementação do proxy de recuperação de desastres do BlueXP  requer comunicação da porta 443 entre o conetor e quaisquer vCenter Servers e arrays ONTAP usando um protocolo HTTPS. O agente de recuperação de desastres do BlueXP  no conetor se comunica diretamente com o VMware vSphere, o VC ou o ONTAP ao executar qualquer ação.

Para obter mais informações sobre o proxy inteligente para recuperação de desastres do BlueXP , https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["Configure sua infraestrutura para recuperação de desastres no BlueXP"] consulte .

Para obter mais informações sobre a configuração geral do proxy no BlueXP , https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Configure um conetor para usar um servidor proxy"^] consulte .



==== Termine o teste gratuito a qualquer momento

Você pode parar o teste gratuito em qualquer dente ou você pode esperar até que ele expire.

 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["Termine a avaliação gratuita"]Consulte .



=== 19 de fevereiro de 2025

Versão 4,2



==== Suporte ao ASA R2 para VMs e armazenamentos de dados no storage VMFS

Essa versão da recuperação de desastres do BlueXP  oferece suporte ao ASA R2 para VMs e armazenamentos de dados no storage VMFS. Em um sistema ASA R2, o software ONTAP oferece suporte à funcionalidade essencial de SAN e remove recursos não suportados em ambientes SAN.

Esta versão suporta os seguintes recursos para o ASA R2:

* Provisionamento de grupo de consistência para armazenamento primário (apenas grupo de consistência plana, ou seja, apenas um nível sem estrutura hierárquica)
* Operações de backup (grupo de consistência), incluindo automação de SnapMirror


O suporte ao ASA R2 na recuperação de desastres do BlueXP  usa o ONTAP 9.16.1.

Embora os datastores possam ser montados em um volume ONTAP ou em uma unidade de armazenamento ASA R2, um grupo de recursos na recuperação de desastres do BlueXP  não pode incluir um datastore do ONTAP e um do ASA R2. Você pode selecionar um datastore do ONTAP ou um datastore do ASA R2 em um grupo de recursos.



=== 30 de outubro de 2024



==== Relatórios

Agora você pode gerar e baixar relatórios para ajudá-lo a analisar seu cenário. Os relatórios pré-projetados resumem failovers e failbacks, mostram detalhes de replicação em todos os locais e mostram os detalhes da tarefa nos últimos sete dias.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Criar relatórios de recuperação de desastres"].



==== teste gratuito de 30 dias

Agora você pode se inscrever para uma avaliação gratuita de 30 dias da recuperação de desastres do BlueXP . Anteriormente, as avaliações gratuitas duravam 90 dias.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configure o licenciamento"].



==== Desativar e ativar planos de replicação

Uma versão anterior incluiu atualizações da estrutura de agendamento de teste de failover, que era necessária para dar suporte a programações diárias e semanais. Esta atualização exigiu que você desabilite e reative todos os planos de replicação existentes para que você possa usar as novas programações de teste de failover diárias e semanais. Este é um requisito único.

Veja como:

. No menu superior, selecione *planos de replicação*.
. Selecione um plano e selecione o ícone ações para exibir o menu suspenso.
. Selecione *Desativar*.
. Após alguns minutos, selecione *Enable* (Ativar).




==== Mapeamento de pastas

Quando você cria um plano de replicação e mapeia recursos de computação, agora é possível mapear pastas para que as VMs sejam recuperadas em uma pasta especificada para datacenter, cluster e host.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



==== Detalhes da VM disponíveis para failover, failback e failover de teste

Quando uma falha ocorre e você está iniciando um failover, executando um failback ou testando o failover, agora você pode ver detalhes das VMs e identificar quais VMs não reiniciaram.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover de aplicativos para um local remoto"].



==== Atraso de inicialização da VM com sequência de inicialização ordenada

Quando você cria um plano de replicação, agora você pode definir um atraso de inicialização para cada VM no plano. Isso permite que você defina uma sequência para que as VMs comecem a garantir que todas as VMs prioritárias One estejam sendo executadas antes que as VMs prioritárias subsequentes sejam iniciadas.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



==== Informações do sistema operacional da VM

Quando você cria um plano de replicação, agora você pode ver o sistema operacional de cada VM no plano. Isso é útil para decidir como agrupar VMs em um grupo de recursos.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



==== Alias de nome da VM

Quando você cria um plano de replicação, agora é possível adicionar um prefixo e sufixo aos nomes da VM no SIT de recuperação de desastres. Isso permite que você use um nome mais descritivo para as VMs no plano.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



==== Limpe os instantâneos antigos

Você pode excluir todos os snapshots que não forem mais necessários além da contagem de retenção especificada. Os snapshots podem se acumular ao longo do tempo quando você diminui a contagem de retenção de snapshots, e agora você pode removê-los para liberar espaço. Você pode fazer isso a qualquer momento sob demanda ou quando você excluir um plano de replicação.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gerencie sites, grupos de recursos, planos de replicação, armazenamentos de dados e informações de máquinas virtuais"] consulte .



==== Reconciliar instantâneos

Agora você pode reconciliar snapshots que estão fora de sincronia entre a origem e o destino. Isso pode ocorrer se os snapshots forem excluídos em um destino fora da recuperação de desastres do BlueXP . O serviço exclui o instantâneo na origem automaticamente a cada 24 horas. No entanto, você pode executar isso sob demanda. Esse recurso permite que você garanta que os snapshots sejam consistentes em todos os sites.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gerenciar planos de replicação"] consulte .



== Sistemas e-Series



=== 18 de setembro de 2022



==== Suporte para e-Series

Agora você pode descobrir seus sistemas e-Series diretamente da BlueXP . Descobrir sistemas e-Series oferece uma visão completa dos dados em sua multicloud híbrida.



== Eficiência económica



=== 15 de maio de 2024



==== Funcionalidades desativadas

Alguns recursos de eficiência econômica do BlueXP  foram temporariamente desativados:

* Atualização de tecnologia
* Adicionar capacidade




=== 14 de março de 2024



==== Opções de atualização de tecnologia

Se você tiver ativos existentes e quiser determinar se uma tecnologia precisa ser atualizada, use as opções de atualização da tecnologia de eficiência econômica da BlueXP . Você pode analisar uma breve avaliação de suas cargas de trabalho atuais e obter recomendações ou, se você enviou logs do AutoSupport para o NetApp nos últimos 90 dias, o serviço agora pode fornecer uma simulação de workload para ver como suas cargas de trabalho funcionam no novo hardware.

Você também pode adicionar um workload e excluir cargas de trabalho existentes da simulação.

Anteriormente, você só poderia fazer uma avaliação de seus ativos e identificar se uma atualização de tecnologia é recomendada.

O recurso agora faz parte da opção de atualização técnica na navegação à esquerda.

Saiba mais sobre o https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Avalie uma atualização de tecnologia"].



=== 08 de novembro de 2023



==== Atualização de tecnologia

Esta versão da eficiência econômica do BlueXP  inclui uma nova opção para fazer uma avaliação de seus ativos e identificar se uma atualização de tecnologia é recomendada. O serviço inclui uma nova opção de atualização técnica na navegação à esquerda, novas páginas onde você pode fazer uma avaliação de suas cargas de trabalho e ativos atuais e um relatório que fornece recomendações para você.



== Armazenamento em cache na borda

O serviço de cache BlueXP  Edge foi removido em 7 de agosto de 2024.



== Google Cloud Storage



=== 10 de julho de 2023



==== Capacidade de adicionar novos buckets e gerenciar buckets existentes do BlueXP

Você já teve a capacidade de visualizar os buckets do Google Cloud Storage no BlueXP  Canvas por algum tempo. Agora você pode adicionar novos buckets e alterar propriedades para buckets existentes diretamente do BlueXP . https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["Veja como adicionar novos buckets do Google Cloud Storage"].



== Kubernetes

O suporte à descoberta e ao gerenciamento de clusters do Kubernetes foi removido em 7 de agosto de 2024.



== Relatórios de migração

O serviço de relatórios de migração do BlueXP  foi removido em 7 de agosto de 2024.



== Clusters ONTAP no local



=== 26 de novembro de 2024



==== Suporte para sistemas ASA R2 com modo privado

Agora você pode descobrir os sistemas NetApp ASA R2 ao usar o BlueXP  no modo privado. Este suporte está disponível a partir da versão 3.9.46 do modo privado do BlueXP .

* https://docs.netapp.com/us-en/asa-r2/index.html["Saiba mais sobre os sistemas ASA R2"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Saiba mais sobre os modos de implantação do BlueXP "^]




=== 7 de outubro de 2024



==== Suporte para sistemas ASA R2

Agora você pode descobrir os sistemas NetApp ASA R2 no BlueXP  ao usar o BlueXP  no modo padrão ou no modo restrito. Depois de descobrir um sistema NetApp ASA R2 e abrir o ambiente de trabalho, você será levado diretamente para o Gerenciador de sistemas.

Não há outras opções de gerenciamento disponíveis com os sistemas ASA R2. Não é possível usar a visualização padrão e não é possível ativar os serviços BlueXP .

A descoberta de sistemas ASA R2 não é suportada ao usar o BlueXP  no modo privado.

* https://docs.netapp.com/us-en/asa-r2/index.html["Saiba mais sobre os sistemas ASA R2"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Saiba mais sobre os modos de implantação do BlueXP "^]




=== 22 de abril de 2024



==== Modelos de volume já não são suportados

Você não pode mais criar um volume a partir de um modelo. Essa ação foi associada ao serviço de correção do BlueXP , que não está mais disponível.



== Resiliência operacional



=== 02 de abril de 2023



==== Serviço de resiliência operacional do BlueXP

Com o novo serviço de resiliência operacional da BlueXP  e as sugestões de correção automatizada de risco operacional de TI, você pode implementar as correções sugeridas antes que ocorra uma interrupção ou falha.

A resiliência operacional é um serviço que ajuda você a analisar alertas e eventos para manter a integridade, o tempo de atividade e a performance de serviços e soluções.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["Saiba mais sobre a resiliência operacional do BlueXP "].



== Proteção contra ransomware



=== 29 de abril de 2025



==== Suporte para o Amazon FSX for NetApp ONTAP

Esta versão suporta o Amazon FSX for NetApp ONTAP. Esse recurso ajuda você a proteger suas cargas de trabalho do FSX for ONTAP com proteção contra ransomware BlueXP .

O FSX para ONTAP é um serviço totalmente gerenciado que fornece o poder do armazenamento NetApp ONTAP na nuvem. Ele oferece os mesmos recursos, performance e funcionalidades administrativas que você usa no local com a agilidade e escalabilidade de um serviço AWS nativo.

As seguintes alterações foram feitas no fluxo de trabalho de proteção contra ransomware do BlueXP :

* A descoberta inclui cargas de trabalho no FSX para ambientes de trabalho do ONTAP 9,15.
* A guia proteção mostra as cargas de trabalho nos ambientes FSX for ONTAP. Nesse ambiente, você deve executar operações de backup usando o serviço de backup do FSX for ONTAP. É possível restaurar esses workloads usando snapshots de proteção contra ransomware da BlueXP .
+

TIP: As políticas de backup para uma carga de trabalho em execução no FSX for ONTAP não podem ser definidas no BlueXP . Todas as políticas de backup existentes definidas no Amazon FSX for NetApp ONTAP permanecem inalteradas.

* Incidentes de alerta mostram o novo ambiente de trabalho do FSX for ONTAP.


Para obter detalhes, https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["Saiba mais sobre a proteção contra ransomware BlueXP  e os ambientes de trabalho"] consulte .

Para obter informações sobre as opções suportadas, consulte o https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["Limitações da proteção contra ransomware do BlueXP"].



=== 14 de abril de 2025



==== Relatórios de exercícios de prontidão

Com esse lançamento, você pode analisar os relatórios de exercícios de prontidão de ataques de ransomware. Um exercício de prontidão permite simular um ataque de ransomware em um workload de amostra recém-criado. Em seguida, investigue o ataque simulado e recupere a carga de trabalho de amostra. Esse recurso ajuda você a saber que está preparado no caso de um ataque real de ransomware, testando processos de notificação, resposta e recuperação de alertas.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Faça um exercício de prontidão para ataques de ransomware"] consulte .



==== Novas funções e permissões de controle de acesso baseadas em funções

Anteriormente, você poderia atribuir funções e permissões a usuários com base em suas responsabilidades, o que ajuda a gerenciar o acesso de usuários à proteção contra ransomware do BlueXP . Com esta versão, há duas novas funções específicas para a proteção contra ransomware do BlueXP  com permissões atualizadas. As novas funções são:

* Administração de proteção contra ransomware
* Visualizador de proteção contra ransomware


Para obter detalhes sobre permissões, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["Acesso baseado em funções à proteção contra ransomware da BlueXP  aos recursos"] consulte .



==== Melhorias de pagamento

Esta versão inclui várias melhorias no processo de pagamento.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["Configure opções de licenciamento e pagamento"] consulte .



=== 10 de março de 2025



==== Simule um ataque e responda

Com esse lançamento, simule um ataque de ransomware para testar sua resposta a um alerta de ransomware. Esse recurso ajuda você a saber que está preparado no caso de um ataque real de ransomware, testando processos de notificação, resposta e recuperação de alertas.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Faça um exercício de prontidão para ataques de ransomware"] consulte .



==== Melhorias no processo de descoberta

Esta versão inclui melhorias nos processos seletivos de descoberta e redescoberta:

* Com esta versão, você pode descobrir cargas de trabalho recém-criadas que foram adicionadas aos ambientes de trabalho selecionados anteriormente.
* Você também pode selecionar _new_ ambientes de trabalho nesta versão. Esse recurso ajuda a proteger novos workloads adicionados ao seu ambiente.
* Você pode executar esses processos de descoberta durante o processo de descoberta inicialmente ou dentro da opção Configurações.


Para obter mais informações, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Descubra cargas de trabalho recém-criadas para ambientes de trabalho selecionados anteriormente"] consulte e https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Configure recursos com a opção Configurações"].



==== Alertas levantados quando a criptografia alta é detetada

Com essa versão, você pode visualizar alertas quando a alta criptografia é detetada em suas cargas de trabalho, mesmo sem alterações de extensão de arquivo alta. Esse recurso, que usa o ONTAP Autonomous ransomware Protection (ARP) AI, ajuda a identificar cargas de trabalho que correm risco de ataques de ransomware. Use esse recurso e baixe toda a lista de arquivos afetados com ou sem alterações de extensão.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Responda a um alerta de ransomware detetado"] consulte .



=== 16 de dezembro de 2024



==== Detecte um comportamento anômalo do usuário usando a segurança de workloads de storage do Data Infrastructure Insights

Com esta versão, você pode usar a segurança de workload de storage do Data Infrastructure Insights para detectar um comportamento incomum dos usuários em seus workloads de storage. Esse recurso ajuda você a identificar possíveis ameaças à segurança e bloquear usuários potencialmente maliciosos para proteger seus dados.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Responda a um alerta de ransomware detetado"] consulte .

Antes de usar a segurança de workload de storage para detectar comportamento anômalo do usuário, você precisa configurar a opção usando a opção *Configurações* de proteção contra ransomware da BlueXP .

Consulte a https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Configurar as configurações de proteção contra ransomware do BlueXP"].



==== Selecione workloads para descobrir e proteger

Com esta versão, agora você pode fazer o seguinte:

* Em cada conetor, selecione os ambientes de trabalho onde você deseja descobrir cargas de trabalho. Você pode se beneficiar desse recurso se quiser proteger cargas de trabalho específicas em seu ambiente e não em outros.
* Durante a descoberta do workload, é possível habilitar a detecção automática de workloads por conector. Esse recurso permite selecionar as cargas de trabalho que você deseja proteger.
* Descubra cargas de trabalho recém-criadas para ambientes de trabalho selecionados anteriormente.


Consulte a https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Localizar workloads"].



== Remediação

O serviço de remediação BlueXP  foi removido em 22 de abril de 2024.



== Replicação



=== 18 de setembro de 2022



==== FSX para ONTAP para Cloud Volumes ONTAP

Agora você pode replicar dados de um sistema de arquivos do Amazon FSX for ONTAP para o Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Saiba como configurar a replicação de dados"].



=== 31 de julho de 2022



==== FSX para ONTAP como a fonte de dados

Agora você pode replicar dados de um sistema de arquivos do Amazon FSX for ONTAP para os seguintes destinos:

* Amazon FSX para ONTAP
* Cluster ONTAP on-premises


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Saiba como configurar a replicação de dados"].



=== 2 de setembro de 2021



==== Suporte para o Amazon FSX for ONTAP

Agora você pode replicar dados de um sistema Cloud Volumes ONTAP ou cluster do ONTAP no local para um sistema de arquivos do Amazon FSX for ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Saiba como configurar a replicação de dados"].



== Atualizações de software



=== 02 de abril de 2025



==== Riscos atenuados

Na seção de resumo das atualizações de software do BlueXP , agora você pode ver o número total de riscos que podem ser mitigados pela atualização do sistema operacional. Isso permite que os usuários avaliem as melhorias de segurança e estabilidade em sua base de instalação.



=== 07 de agosto de 2024



==== Atualização do ONTAP

O serviço de atualizações de software da BlueXP  fornece uma experiência de atualização contínua aos usuários, mitigando riscos e garantindo que os clientes possam aproveitar totalmente os recursos do ONTAP.

Saiba mais link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Atualizações de software BlueXP"]sobre o .



== StorageGRID



=== 7 de agosto de 2024



==== Nova vista avançada

A partir do StorageGRID 11,8, você pode usar a interface familiar do Gerenciador de Grade para gerenciar seu sistema StorageGRID a partir do BlueXP .

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Saiba como administrar o StorageGRID usando a exibição avançada"].



==== Capacidade de analisar e aprovar o certificado da interface de gerenciamento do StorageGRID

Agora você pode analisar e aprovar um certificado de interface de gerenciamento do StorageGRID ao descobrir o sistema StorageGRID do BlueXP . Você também pode revisar e aprovar o certificado de interface de gerenciamento StorageGRID mais recente em uma grade descoberta.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Saiba como analisar e aprovar o certificado do servidor durante a descoberta do sistema."]



=== 18 de setembro de 2022



==== Suporte para StorageGRID

Agora você pode descobrir seus sistemas StorageGRID diretamente da BlueXP . Ao descobrir o StorageGRID, você obtém uma visão completa dos dados na multicloud híbrida.



== Disposição em camadas



=== 9 de agosto de 2023



==== Use um prefixo personalizado para o nome do bucket

No passado, você precisava usar o prefixo padrão "Fabric-pool" ao definir o nome do bucket, por exemplo, _Fabric-pool-bucket1_. Agora você pode usar um prefixo personalizado ao nomear seu bucket. Esse recurso está disponível somente ao categorizar dados no Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Saiba mais"].



==== PESQUISE um cluster em todos os conetores BlueXP 

Se você estiver usando vários conetores para gerenciar todos os sistemas de storage no ambiente, alguns clusters nos quais você deseja implementar a disposição em camadas podem estar em conetores diferentes. Se você não tiver certeza de qual conetor está gerenciando um determinado cluster, poderá pesquisar em todos os conetores usando a disposição em camadas do BlueXP . https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Saiba mais"].



=== 4 de julho de 2023



==== Ajuste a largura de banda para transferir dados inativos

Ao ativar a disposição em camadas do BlueXP , o ONTAP pode usar uma quantidade ilimitada de largura de banda da rede para transferir os dados inativos de volumes no cluster para o storage de objetos. Se você notar que a disposição em categorias de tráfego está afetando as cargas de trabalho normais do usuário, poderá controlar a quantidade de largura de banda que pode ser usada durante a transferência. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Saiba mais"].



==== Evento de disposição em camadas exibido no Centro de notificações

O evento de disposição em camadas "armazene dados adicionais do cluster <name> ao storage de objetos para aumentar a eficiência de storage" agora aparece como uma notificação quando um cluster está em camadas menos de 20% dos dados inativos, incluindo clusters que não estão em camadas.

Esta notificação é uma "recomendação" para ajudar a tornar seus sistemas mais eficientes e economizar nos custos de armazenamento. Ele fornece um link para o https://bluexp.netapp.com/cloud-tiering-service-tco["Calculadora de economia e custo total de propriedade em camadas do BlueXP "^] para ajudá-lo a calcular suas economias de custo.



=== 3 de abril de 2023



==== O separador Licenciamento foi removido

A guia Licenciamento foi removida da interface de disposição em camadas do BlueXP . Todo o licenciamento para assinaturas de pagamento conforme o uso (PAYGO) é acessado a partir do Painel no local de disposição em camadas do BlueXP  agora. Também há um link dessa página para a carteira digital da BlueXP  para que você possa visualizar e gerenciar qualquer BYOL (bring-your-own-licenses) em camadas do BlueXP .



==== As guias de disposição em camadas foram renomeadas e atualizadas

A guia "Painel de clusters" foi renomeada para "clusters" e a guia "Visão geral on-Prem" foi renomeada para "Painel on-premises". Essas páginas adicionaram algumas informações que o ajudarão a avaliar se você pode otimizar seu espaço de armazenamento com configuração adicional de disposição em camadas.



== Armazenamento em cache de volume



=== 04 de junho de 2023



==== Armazenamento em cache de volume

O armazenamento em cache de volume, um recurso do software ONTAP 9, é um recurso de armazenamento em cache remoto que simplifica a distribuição de arquivos, reduz a latência da WAN ao aproximar os recursos de seus usuários e recursos de computação e reduz os custos de largura de banda da WAN. O armazenamento em cache de volume fornece um volume persistente e gravável em um local remoto. Você pode usar o armazenamento em cache de volume do BlueXP  para acelerar o acesso aos dados ou descarregar tráfego de volumes acessados com muita frequência. Os volumes de cache são ideais para cargas de trabalho com uso intenso de leitura, especialmente quando os clientes precisam acessar os mesmos dados repetidamente.

Com o armazenamento em cache de volume do BlueXP , você tem funcionalidades de armazenamento em cache para a nuvem, especificamente para o Amazon FSX for NetApp ONTAP, Cloud Volumes ONTAP e ambientes locais como trabalho.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Saiba mais sobre o armazenamento em cache de volume do BlueXP "].



== Fábrica de carga de trabalho



=== 04 de maio de 2025



==== Suporte autocompleto do CloudShell

Ao usar o CloudShell de fábrica de carga de trabalho do BlueXP , você pode começar a digitar um comando e pressionar a tecla Tab para exibir as opções disponíveis. Se houver várias possibilidades, a CLI exibirá uma lista de sugestões. Esse recurso aumenta a produtividade minimizando erros e acelerando a execução de comandos.



==== Terminologia de permissões atualizada

A interface do usuário e a documentação de fábrica da carga de trabalho agora usam "somente leitura" para se referir a permissões de leitura e "leitura-gravação" para se referir a permissões de automação.



=== 30 de março de 2025



==== O CloudShell relata respostas de erro geradas por IA para os comandos da CLI do ONTAP

Ao usar o CloudShell, cada vez que você emite um comando ONTAP CLI e um erro ocorre, você pode obter respostas de erro geradas por IA que incluem uma descrição da falha, a causa da falha e uma resolução detalhada.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Use o CloudShell"]



==== IAM:Atualização de permissão SimulatePermissionPolicy

Agora você pode gerenciar a `iam:SimulatePrincipalPolicy` permissão no console de fábrica de workload ao adicionar credenciais adicionais de conta da AWS ou adicionar uma nova funcionalidade de workload, como o workload do GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de alteração de referência de permissões"]



=== 02 de fevereiro de 2025



==== CloudShell disponível no console de fábrica da carga de trabalho do BlueXP

O CloudShell está disponível em qualquer lugar no console de fábrica de carga de trabalho do BlueXP . O CloudShell permite que você use as credenciais da AWS e do ONTAP fornecidas na sua conta do BlueXP  e execute os comandos da CLI da AWS ou da CLI do ONTAP em um ambiente semelhante ao shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Use o CloudShell"]



==== Atualização de permissões para bancos de dados

A seguinte permissão está agora disponível no modo _read_ para bancos de dados: `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de alteração de referência de permissões"]
