= 3-2-1 criação de política de backup durante a ativação do backup
:allow-uri-read: 




=== 3-2-1 criação de política de backup durante a ativação do backup

Anteriormente, políticas personalizadas precisavam ser criadas antes de iniciar um Snapshot, replicação ou backup. Agora você pode criar uma política durante o processo de ativação do backup usando a IU de backup e recuperação do BlueXP .

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Saiba mais sobre políticas"].



=== Suporte para restauração rápida sob demanda de volumes ONTAP

O backup e a recuperação do BlueXP  agora permitem executar uma "restauração rápida" de um volume do storage de nuvem para um sistema Cloud Volumes ONTAP. A restauração rápida é ideal para situações de recuperação de desastres em que você precisa fornecer acesso a um volume o mais rápido possível. Uma restauração rápida restaura os metadados do arquivo de backup para um volume em vez de restaurar todo o arquivo de backup.

O sistema de destino do Cloud Volumes ONTAP deve estar executando o ONTAP versão 9.13.0 ou superior. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Saiba mais sobre como restaurar dados"].

O Monitor de trabalhos de cópia de segurança e recuperação do BlueXP  também mostra informações sobre o progresso dos trabalhos de restauro rápido.
